# Compiler and flags
CXX = g++
CXXFLAGS =
EIGEN_INCLUDE = -I/usr/local/include/eigen3

# Default source (can be overridden via command line)
SRC ?= chebyshev_schro3.cpp
TARGET ?= main

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $(EIGEN_INCLUDE) $^ -o $@

clean:
	rm -f $(TARGET)
