# Compiler and flags
CXX = g++
CXXFLAGS =
ROOT_FLAGS = $(shell root-config --cflags --libs)

# Default source (can be overridden)
SRC ?= main_root.cpp
TARGET ?= main

all: $(TARGET)

$(TARGET): $(SRC)
	$(CXX) $(CXXFLAGS) $^ $(ROOT_FLAGS) -o $@

clean:
	rm -f $(TARGET)
